// <auto-generated />
namespace vsmartsell_test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ignore_accent_userfullname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignore_accent_userfullname));
        
        string IMigrationMetadata.Id
        {
            get { return "201509151041524_ignore_accent_userfullname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
