// <auto-generated />
namespace vsmartsell_test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class upgrade_LSGD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upgrade_LSGD));
        
        string IMigrationMetadata.Id
        {
            get { return "201508200932460_upgrade_LSGD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
