// <auto-generated />
namespace vsmartsell_test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class banggia_add_magoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banggia_add_magoi));
        
        string IMigrationMetadata.Id
        {
            get { return "201509171117226_banggia_add_magoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
